### ISSUE TITLE
grpc需要连接池吗？

### ISSUE THREAD

**Issue by wjzhangcsu** [0x5010/grpcp#1]
grpc需要连接池吗？这个连接池会断了重连吗？跟默认的连接方式相比，有什么优势吗？

**Comment by 0x5010** [comment]
1.多个rpc任务可以复用同一个连接，不用占用多个连接。而且在分布式系统中，网络复杂变化的情况需要选择还存活的连接进行使用。
2.不会在GetConn的时候或从连接池取出ready的连接，如果是新连接或shutdown的连接会重新测试建连，建立成功会保持长连接和心跳。如果是偶然的中间状态，则会在心跳检测中检测直到状态变成ready或超时被shutdown
3.同上。
