### ISSUE TITLE
HI，我使用的beego框架，这样的使用方法是否正确？

### ISSUE THREAD

**Issue by saisaixv** [0x5010/grpcp#2]
这是在controller中的一个post方法，每个用户注册都会执行一遍该方法，在高并发的情况下这样使用可以的是吗？

func (this *RegisterController) Post() {

    conn, _ := grpcp.GetConn(addr)  // get conn with grpcp default pool
    // defer conn.Close()  // no close, close will disconnect
    client := pb.NewGreeterClient(conn)
    r, _ := client.SayHello(context.Background(), &pb.HelloRequest{Name: name})
}

**Comment by 0x5010** [comment]
刚刚更新了个版本，针对你的场景加了个Dial方法。如下使用，
```go
conn, err := grpcp.GetConn(addr)  // 获取已有或创建连接
    if err != nil {
         conn, err = grpcp.Dial(addr) // 强制重新创建连接，创建成功的连接可以被GetConn使用
}
```

或
```go
pool := grpcp.New(...)
conn, err := pool.GetConn(addr)  
    if err != nil {
         conn, err = pool.Dial(addr) 
}
```

**Comment by saisaixv** [comment]
好的，谢谢大神
